import { useRef, useState } from "react";
import FarmerForm from "./FarmerForm";
import RecommendationResults from "./RecommendationResults";
import FreshnessPanel from "./FreshnessPanel";
import SupplierRankingPanel from "./SupplierRankingPanel";
import LogisticsOptimizerPanel from "./LogisticsOptimizerPanel";
import FarmerMarketplace from "./FarmerMarketplace";
import { getRecommendations } from "../api/recommendations";
import type { FarmerRecommendationRequest, RecommendationResponse } from "../api/recommendations";

type FarmerTab = "overview" | "profile" | "crop" | "freshness" | "listings" | "matching" | "logistics";
const FARM_NAV: Array<[FarmerTab,string,string]> = [["overview","Farm overview","⌂"],["profile","Farmer profiles","♟"],["crop","Crop recommendation","♧"],["freshness","Produce freshness","◎"],["listings","Market listings","◫"],["matching","Buyer matching demo","✦"],["logistics","Transport planning","⇢"]];
const FARM_COPY: Record<FarmerTab,[string,string]> = { overview:["Farmer command center","Plan crops, prove quality, reach buyers, and optimize delivery from one workspace."], profile:["Connected farmer data","Review farms, soil context, goals, and registered produce."], crop:["What should I grow?","Get feasible and explainable crop recommendations from your farm conditions."], freshness:["Check produce freshness","Use the trained tomato model to grade produce before listing or dispatch."], listings:["Farmer marketplace","See how verified produce appears to connected buyers."], matching:["Buyer requirement matching","Test how your lot ranks against price, quality, quantity, freshness, and reliability."], logistics:["Delivery planning","Compare direct, pooled, and collection-hub transport with landed cost."] };

export default function FarmerDashboard({ onHome, onBuyer }: { onHome:()=>void; onBuyer:()=>void }) {
  const [active,setActive]=useState<FarmerTab>("overview"); const [menu,setMenu]=useState(false); const [results,setResults]=useState<RecommendationResponse|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const ref=useRef<HTMLDivElement>(null);
  const go=(tab:FarmerTab)=>{setActive(tab);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
  const submit=async(payload:FarmerRecommendationRequest)=>{setLoading(true);setError(null);try{setResults(await getRecommendations(payload));setTimeout(()=>ref.current?.scrollIntoView({behavior:"smooth"}),100)}catch(e){setError(e instanceof Error?e.message:"Unable to recommend crops")}finally{setLoading(false)}};
  return <div className="farmer-app">{menu&&<button className="sidebar-scrim" onClick={()=>setMenu(false)} aria-label="Close navigation"/>}<aside className={`farmer-sidebar ${menu?"open":""}`}><div className="buyer-brand"><span>♧</span><b>AgriOptima</b><button onClick={()=>setMenu(false)}>×</button></div><div className="workspace-card"><span>RK</span><div><b>Ramesh Kumar</b><small>Farmer workspace</small></div><i>⌄</i></div><nav><p>Farm intelligence</p>{FARM_NAV.map(([key,label,icon])=><button key={key} className={active===key?"active":""} onClick={()=>go(key)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-status"><span>● Farm connected</span><strong>6 tools ready</strong><small>Plan · Grade · Sell · Deliver</small><button onClick={onHome}>← Public landing page</button></div></aside><main className="farmer-main"><header className="buyer-topbar"><button className="mobile-nav" onClick={()=>setMenu(true)}>☰</button><div className="global-search">⌕ <input placeholder="Search farm tools, crops, listings…"/><kbd>⌘ K</kbd></div><div className="portal-switch"><button onClick={onHome}>Home</button><button onClick={onBuyer}>Buyer portal</button></div><div className="buyer-person"><span>RK</span><div><b>Ramesh Kumar</b><small>Verified farmer</small></div><i>⌄</i></div></header><div className="buyer-content"><section className="buyer-heading"><div><span>Farm intelligence · Connected</span><h1>{FARM_COPY[active][0]}</h1><p>{FARM_COPY[active][1]}</p></div>{active!=="overview"&&<button onClick={()=>go("overview")}>← Farm overview</button>}</section>
    {active==="overview"&&<><section className="farmer-welcome"><div><span>✦ Personalized farmer workspace</span><h2>Grow with evidence.<br/><em>Sell with confidence.</em></h2><p>Your soil, farm goals, produce quality, buyer access, and delivery planning are connected to the same intelligence network.</p><button onClick={()=>go("crop")}>Build my crop plan →</button></div><div className="farmer-quick">{[["3.5","Acres registered"],["2","Active crop listings"],["6.8","Soil pH"],["₹80k","Investment budget"]].map(([v,l])=><span key={l}><b>{v}</b><small>{l}</small></span>)}</div></section><section className="model-demo-grid">{FARM_NAV.slice(2).map(([key,label,icon])=><button key={key} onClick={()=>go(key)}><span>{icon}</span><div><b>{label}</b><small>{FARM_COPY[key][1]}</small></div><i>Open demo →</i></button>)}</section></>}
    {active==="profile"&&<FarmerMarketplace mode="farmers"/>}{active==="freshness"&&<FreshnessPanel/>}{active==="listings"&&<FarmerMarketplace mode="marketplace"/>}{active==="matching"&&<SupplierRankingPanel/>}{active==="logistics"&&<LogisticsOptimizerPanel/>}
    {active==="crop"&&<div className="grid lg:grid-cols-[380px_1fr] gap-6 items-start"><div>{error&&<div className="mb-3 p-3 bg-red-50 text-red-700 text-xs rounded-xl">{error}</div>}<FarmerForm onSubmit={submit} loading={loading}/></div><div ref={ref}>{results?<RecommendationResults data={results}/>:<div className="demo-panel empty-workspace"><span>♧</span><h3>Your recommendation will appear here</h3><p>Submit the connected farm profile to compare feasible crops and expected economics.</p></div>}</div></div>}
  </div><footer className="buyer-footer">Farmer workspace · Crop planning · Freshness · Marketplace · Buyer matching · Logistics</footer></main></div>;
}
