import { LocalizedText } from "../i18n/LocalizedText";
import { useEffect, useState } from "react";

const API = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";
type Farmer = { farmer_id: string; name: string; state: string; district: string; village: string; preferred_language: string; profile_status: string; farm_count: number; listing_count: number; total_area_acres: number; crops: string[] };
type Listing = { listing_id: string; farmer_id: string; farmer_name: string; crop_name: string; crop_variety: string; available_quantity_kg: number; price_per_kg: number; minimum_order_quantity_kg: number; harvest_date?: string; expected_harvest_date?: string; declared_grade: string; packaging_type?: string; district: string; state: string; image_data?: string };
type Detail = { farmer: Farmer; farms: Array<Record<string, string | number | null>>; needs: Record<string, string | number | boolean | null> | null; listings: Listing[] };

export default function FarmerMarketplace({ mode }: { mode: "farmers" | "marketplace" }) {
  const [farmers, setFarmers] = useState<Farmer[]>([]);
  const [listings, setListings] = useState<Listing[]>([]);
  const [selected, setSelected] = useState<Detail | null>(null);
  const [crop, setCrop] = useState("All");
  const [error, setError] = useState("");
  const [mandi,setMandi]=useState<Array<{market:string;district:string;modal_price:number;arrival_date?:string}>>([]);

  useEffect(() => {
    Promise.all([
      fetch(`${API}/marketplace/farmers`).then((r) => { if (!r.ok) throw new Error(); return r.json(); }),
      fetch(`${API}/marketplace/listings`).then((r) => { if (!r.ok) throw new Error(); return r.json(); }),
    ]).then(([f, l]) => { setFarmers(f.farmers || []); setListings(l.listings || []); }).catch(() => setError("Farmer marketplace data is unavailable. Restart the backend and try again."));
  }, []);
  useEffect(()=>{const commodity=crop==="All"?(listings[0]?.crop_name||"Tomato"):crop;if(!commodity)return;fetch(`${API}/marketplace/mandi-prices?crop=${encodeURIComponent(commodity)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>setMandi(d.prices||[])).catch(()=>setMandi([]))},[crop,listings]);

  const openFarmer = async (id: string) => {
    const response = await fetch(`${API}/marketplace/farmers/${id}`);
    if (response.ok) setSelected(await response.json());
  };
  const crops = ["All", ...Array.from(new Set(listings.map((item) => item.crop_name)))];
  const shown = crop === "All" ? listings : listings.filter((item) => item.crop_name === crop);

  if (error) return <div className="demo-panel text-sm text-red-600"><LocalizedText source={"{0}"} values={[error]} /></div>;
  return <div className="space-y-5">
    {mode === "marketplace" && <>
      <div className="market-filter"><div><b><LocalizedText source={"Verified produce marketplace"} /></b><small><LocalizedText source={"{0} available listings from {1} farmers"} values={[listings.length, farmers.length]} /></small></div><div>{crops.map((item) => <button key={item} onClick={() => setCrop(item)} className={crop === item ? "active" : ""}><LocalizedText source={"{0}"} values={[item]} /></button>)}</div></div>
      <section className="mandi-strip"><div><b><LocalizedText source={"Latest mandi prices"} /></b><small><LocalizedText source={"AGMARKNET data · price per kg"} /></small></div>{mandi.length?mandi.slice(0,4).map((m,i)=><article key={`${m.market}-${i}`}><small><LocalizedText source={"{0}"} values={[m.market||m.district]} /></small><b><LocalizedText source={"₹{0}/kg"} values={[(Number(m.modal_price)/100).toFixed(2)]} /></b><span><LocalizedText source={"{0}"} values={[m.arrival_date||"Latest available"]} /></span></article>):<p><LocalizedText source={"Live mandi data is unavailable; farmer prices remain visible below."} /></p>}</section>
      <div className="listing-grid">{shown.map((listing) => <article key={listing.listing_id} className="listing-card"><div className="produce-visual">{listing.image_data?<img src={listing.image_data} alt={`${listing.crop_name} listed by ${listing.farmer_name}`} onError={e=>{e.currentTarget.style.display="none"}}/>:<span><LocalizedText source={"{0}"} values={[listing.crop_name === "Tomato" ? "🍅" : listing.crop_name === "Onion" ? "🧅" : listing.crop_name === "Orange" ? "🍊" : "🌾"]} /></span>}<i><LocalizedText source={"{0}"} values={[listing.declared_grade.replace("GRADE_", "Grade ")]} /></i></div><div className="p-5"><span className="text-[10px] uppercase tracking-wider text-[#26483E]"><LocalizedText source={"{0}, {1}"} values={[listing.district, listing.state]} /></span><h3><LocalizedText source={"{0} · {1}"} values={[listing.crop_name, listing.crop_variety]} /></h3><button onClick={() => openFarmer(listing.farmer_id)}><LocalizedText source={"{0}"} values={[listing.farmer_name]} /></button><div className="listing-numbers"><span><small><LocalizedText source={"Available"} /></small><b><LocalizedText source={"{0} kg"} values={[listing.available_quantity_kg.toLocaleString("en-IN")]} /></b></span><span><small><LocalizedText source={"Farmer price"} /></small><b><LocalizedText source={"₹{0}/kg"} values={[listing.price_per_kg]} /></b></span></div><div className="listing-footer"><span><LocalizedText source={"Min. order {0} kg"} values={[listing.minimum_order_quantity_kg]} /></span><button onClick={() => openFarmer(listing.farmer_id)}><LocalizedText source={"View supplier →"} /></button></div></div></article>)}</div>
    </>}
    {mode === "farmers" && <div className="farmer-grid">{farmers.map((farmer) => <article key={farmer.farmer_id} className="farmer-card"><div className="farmer-avatar">{farmer.name.split(" ").map((part) => part[0]).join("")}</div><div className="flex-1"><div className="flex justify-between gap-3"><div><h3><LocalizedText source={"{0}"} values={[farmer.name]} /></h3><p><LocalizedText source={"📍 {0}, {1}"} values={[farmer.village, farmer.district]} /></p></div><span className="verified-pill"><LocalizedText source={"✓ {0}"} values={[farmer.profile_status]} /></span></div><div className="farmer-metrics"><span><b><LocalizedText source={"{0}"} values={[farmer.farm_count]} /></b><small><LocalizedText source={"Farm"} /></small></span><span><b><LocalizedText source={"{0}"} values={[farmer.total_area_acres]} /></b><small><LocalizedText source={"Acres"} /></small></span><span><b><LocalizedText source={"{0}"} values={[farmer.listing_count]} /></b><small><LocalizedText source={"Listings"} /></small></span></div><div className="flex flex-wrap gap-1 mt-4">{farmer.crops.map((item) => <span key={item} className="crop-tag"><LocalizedText source={"{0}"} values={[item]} /></span>)}</div><button onClick={() => openFarmer(farmer.farmer_id)} className="farmer-open"><LocalizedText source={"Open farmer profile →"} /></button></div></article>)}</div>}

    {selected && <div className="profile-overlay" onClick={() => setSelected(null)}><aside onClick={(e) => e.stopPropagation()}><button className="profile-close" onClick={() => setSelected(null)}>×</button><span className="panel-kicker"><LocalizedText source={"Verified farmer profile"} /></span><h2><LocalizedText source={"{0}"} values={[selected.farmer.name]} /></h2><p><LocalizedText source={"📍 {0}, {1}, {2}"} values={[selected.farmer.village, selected.farmer.district, selected.farmer.state]} /></p><section><h3><LocalizedText source={"Farm information"} /></h3>{selected.farms.map((farm) => <div key={String(farm.farm_id)} className="detail-row"><span><LocalizedText source={"{0}"} values={[String(farm.farm_name)]} /></span><b><LocalizedText source={"{0} acres"} values={[String(farm.area_acres)]} /></b><small><LocalizedText source={"Soil pH {0} · {1}"} values={[String(farm.ph ?? "—"), String(farm.irrigation_type ?? "Irrigation not specified")]} /></small></div>)}</section>{selected.needs && <section><h3><LocalizedText source={"Farmer needs"} /></h3><div className="need-grid"><span><LocalizedText source={"Budget "} /><b><LocalizedText source={"₹{0}"} values={[Number(selected.needs.investment_budget || 0).toLocaleString("en-IN")]} /></b></span><span><LocalizedText source={"Goal "} /><b><LocalizedText source={"{0}"} values={[String(selected.needs.primary_goal).replaceAll("_", " ")]} /></b></span><span><LocalizedText source={"Risk preference "} /><b><LocalizedText source={"{0}"} values={[String(selected.needs.risk_preference)]} /></b></span><span><LocalizedText source={"Preferred market "} /><b><LocalizedText source={"{0} km"} values={[String(selected.needs.preferred_market_distance_km)]} /></b></span></div></section>}<section><h3><LocalizedText source={"Crop listings"} /></h3>{selected.listings.map((item) => <div key={item.listing_id} className="detail-row"><span><LocalizedText source={"{0} · {1}"} values={[item.crop_name, item.crop_variety]} /></span><b><LocalizedText source={"{0} kg at ₹{1}/kg"} values={[item.available_quantity_kg, item.price_per_kg]} /></b></div>)}</section></aside></div>}
  </div>;
}
