import { useEffect, useRef, useState } from "react";
import "leaflet/dist/leaflet.css";

const orders=[
  {id:"ORD-2041",shipment:"SHP-2041",crop:"Tomato",qty:"4,000 kg",buyer:"Mehta Foods · Mumbai",status:"In transit",eta:"Today, 2:10 PM",progress:68,from:"Nashik",to:"Mumbai",driver:"Ravi Patil",truck:"MH 15 FT 4821",origin:[20.0059,73.7907] as [number,number],current:[19.6967,73.5609] as [number,number],destination:[19.076,72.8777] as [number,number]},
  {id:"ORD-2043",shipment:"SHP-2043",crop:"Red Onion",qty:"2,500 kg",buyer:"FreshKart Retail · Pune",status:"Pending pickup",eta:"Today, 4:45 PM",progress:18,from:"Lasalgaon",to:"Pune",driver:"Suresh Jadhav",truck:"MH 14 KL 9134",origin:[20.142,74.239] as [number,number],current:[20.05,74.08] as [number,number],destination:[18.5204,73.8567] as [number,number]},
  {id:"ORD-2050",shipment:"SHP-2050",crop:"Orange",qty:"3,200 kg",buyer:"Nagpur Produce Co.",status:"Shipped",eta:"Tomorrow, 8:30 AM",progress:100,from:"Katol",to:"Nagpur",driver:"Amit Wankhede",truck:"MH 31 CQ 2208",origin:[21.2736,78.5858] as [number,number],current:[21.1801,78.92] as [number,number],destination:[21.1458,79.0882] as [number,number]},
];

function ShipmentMap({order}:{order:(typeof orders)[number]}){
  const node=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!node.current)return;let map:import("leaflet").Map|undefined;let cancelled=false;void import("leaflet").then(L=>{if(cancelled||!node.current)return;map=L.map(node.current,{zoomControl:false,scrollWheelZoom:false});L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);L.control.zoom({position:"bottomright"}).addTo(map);const route=[order.origin,order.current,order.destination];L.polyline(route,{color:"#c4f042",weight:6,opacity:.95}).addTo(map);const icon=(kind:string,label:string)=>L.divIcon({className:"farmer-map-marker",html:`<i class="${kind}"></i><b>${label}</b>`,iconSize:[110,34],iconAnchor:[14,17]});L.marker(order.origin,{icon:icon("pickup","Farmer pickup")}).addTo(map);L.marker(order.current,{icon:icon("vehicle",order.status)}).addTo(map);L.marker(order.destination,{icon:icon("buyer","Buyer destination")}).addTo(map);map.fitBounds(L.latLngBounds(route).pad(.22));setTimeout(()=>map?.invalidateSize(),80)});return()=>{cancelled=true;map?.remove()}},[order]);
  return <div className="farmer-map-canvas" ref={node} aria-label={`${order.crop} shipment route map`}/>;
}

export default function FarmerShipments(){
  const [selected,setSelected]=useState<(typeof orders)[number]|null>(null);const shipped=orders.filter(o=>o.status==="Shipped").length;const pending=orders.filter(o=>o.status==="Pending pickup").length;const moving=orders.filter(o=>o.status==="In transit").length;
  return <div className="farmer-orders"><section className="order-status-summary"><article><span>✓</span><b>{shipped}</b><small>Orders shipped</small></article><article><span>↗</span><b>{moving}</b><small>In transit</small></article><article><span>◷</span><b>{pending}</b><small>Pending pickup</small></article><article><span>▣</span><b>{orders.length}</b><small>Total active orders</small></article></section><section className="farmer-order-list"><div><span className="panel-kicker">Order fulfilment</span><h2>Buyer orders and shipments</h2><p>Open any order to view its route map and digital produce passport.</p></div>{orders.map(order=><article key={order.id} onClick={()=>setSelected(order)} onKeyDown={event=>event.key==="Enter"&&setSelected(order)} role="button" tabIndex={0}><div className="order-produce">{order.crop==="Tomato"?"🍅":order.crop.includes("Onion")?"🧅":"🍊"}</div><span><small>{order.id} · {order.shipment}</small><b>{order.qty} {order.crop}</b><em>{order.buyer}</em></span><div className="order-progress"><span><b>{order.status}</b><small>{order.eta}</small></span><div><i style={{width:`${order.progress}%`}}/></div><small>Open map and passport →</small></div></article>)}</section>{selected&&<div className="farmer-tracking-overlay" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()}><button aria-label="Close shipment tracking" onClick={()=>setSelected(null)}>×</button><span className="panel-kicker">Digital produce passport · {selected.shipment}</span><h2>{selected.crop} shipment tracking</h2><p>{selected.qty} · {selected.buyer}</p><ShipmentMap order={selected}/><div className="tracking-facts"><span><small>Status</small><b>{selected.status}</b></span><span><small>Expected arrival</small><b>{selected.eta}</b></span><span><small>Driver</small><b>{selected.driver}</b></span><span><small>Vehicle</small><b>{selected.truck}</b></span></div><div className="passport-checks"><span>✓ Farmer dispatch verified</span><span>✓ Produce passport active</span><span>✓ Buyer tracking synchronized</span></div></section></div>}</div>;
}
