import { LocalizedText } from "../i18n/LocalizedText";
import { useEffect, useState } from "react";

export default function LandingPage({ onBuyer, onFarmer }: { onBuyer:()=>void; onFarmer:()=>void }) {
  const [menu,setMenu]=useState(false); const [scrolled,setScrolled]=useState(false); const [portal,setPortal]=useState(false);
  useEffect(()=>{const handler=()=>setScrolled(window.scrollY>25);window.addEventListener("scroll",handler,{passive:true});return()=>window.removeEventListener("scroll",handler)},[]);
  const openPortal=(kind:"buyer"|"farmer")=>{setMenu(false);setPortal(false);if(kind==="buyer") onBuyer(); else onFarmer()};
  return <div className="agrovia-landing">
    <header className={`landing-header ${scrolled?"scrolled":""}`}><div className="landing-nav"><a href="#top" className="landing-logo"><LocalizedText source={"AgriOptimaᴬᴵ."} /></a><nav><a href="#solutions"><LocalizedText source={"Solutions"} /></a><a href="#platform"><LocalizedText source={"How it works"} /></a><a href="#impact"><LocalizedText source={"Our impact"} /></a><a href="#stories"><LocalizedText source={"Farmer stories"} /></a></nav><div className="landing-actions"><button className="language-button"><LocalizedText source={"EN⌄"} /></button><button onClick={()=>setPortal(true)} className="login-button"><LocalizedText source={"Log in"} /></button><button onClick={()=>setPortal(true)} className="get-started"><LocalizedText source={"Get started"} /></button></div><div className="landing-mobile"><button className="language-button"><LocalizedText source={"EN⌄"} /></button><button id="mobile-menu-toggle-btn" aria-expanded={menu} aria-controls="landing-mobile-menu" onClick={()=>setMenu(!menu)} className="burger-button"><span/><span/><span/></button></div></div>
      {menu&&<div id="landing-mobile-menu" className="landing-mobile-menu"><a onClick={()=>setMenu(false)} href="#solutions"><LocalizedText source={"Solutions"} /></a><a onClick={()=>setMenu(false)} href="#platform"><LocalizedText source={"How it works"} /></a><a onClick={()=>setMenu(false)} href="#impact"><LocalizedText source={"Our impact"} /></a><a onClick={()=>setMenu(false)} href="#stories"><LocalizedText source={"Farmer stories"} /></a><div><button onClick={()=>setPortal(true)}><LocalizedText source={"Log in"} /></button><button onClick={()=>setPortal(true)}><LocalizedText source={"Get started"} /></button></div></div>}
    </header>
    <main id="top"><section className="landing-hero"><div className="hero-backdrop"/><div className="landing-hero-copy"><span><i/><LocalizedText source={" Connected agricultural intelligence"} /></span><h1><LocalizedText source={"Smarter technology"} /><br/><em><LocalizedText source={"for stronger"} /></em><br/><LocalizedText source={"agriculture"} /></h1><p><LocalizedText source={"Connect farm planning, verified supply, AI freshness, buyer credit, supplier matching, and optimized logistics in one transparent platform."} /></p><div><button onClick={()=>setPortal(true)}><LocalizedText source={"Get started today →"} /></button><a href="#platform"><LocalizedText source={"See how it works ▷"} /></a></div><small><LocalizedText source={"Built for farmers, buyers, FPOs, and agricultural supply networks."} /></small></div></section>
      <section className="landing-intro" id="platform"><span><LocalizedText source={"Introducing AgriOptimaᴬᴵ"} /></span><h2><LocalizedText source={"Bringing intelligence to every step of agriculture —"} /></h2><p><LocalizedText source={"We connect farmer data, crop decisions, quality verification, market demand, procurement credit, supplier rankings, and transport economics. Every workflow is explainable, evidence-based, and designed for real production and trade decisions."} /></p><button onClick={()=>setPortal(true)}><LocalizedText source={"Explore the connected platform →"} /></button></section>
      <section className="landing-solutions" id="solutions"><div className="landing-section-head"><span><LocalizedText source={"Connected solutions"} /></span><h2><LocalizedText source={"Smart tools for modern farming and procurement"} /></h2><p><LocalizedText source={"One platform. Two purpose-built workspaces. Every model connected."} /></p></div><div className="solution-grid">{[
        ["🌱","Crop intelligence","Filter infeasible crops and compare transparent opportunity scores.","Farmer planning"],["🍅","AI freshness grading","Grade tomato freshness and inspect produce shipments from images.","Quality assurance"],["📊","Smart procurement","Rank farmer lots against buyer price, quality, quantity, and freshness requirements.","Buyer matching"],["💳","Credit intelligence","Explain buyer risk, repayment behaviour, confidence, and revolving limits.","Trade finance"],["🚚","Logistics optimization","Compare direct, pooled, and collection-hub models with final landed cost.","Supply chain"],["🧺","Verified marketplace","Connect real farmer profiles, farms, needs, and active produce listings.","Market access"],
      ].map(([icon,title,copy,tag])=><article key={title}><span><LocalizedText source={"{0}"} values={[icon]} /></span><small><LocalizedText source={"{0}"} values={[tag]} /></small><h3><LocalizedText source={"{0}"} values={[title]} /></h3><p><LocalizedText source={"{0}"} values={[copy]} /></p><button onClick={()=>setPortal(true)}><LocalizedText source={"Open workspace →"} /></button></article>)}</div></section>
      <section className="landing-process"><div><span><LocalizedText source={"The AgriLoop process"} /></span><h2><LocalizedText source={"Farming smarter"} /><br/><em><LocalizedText source={"starts here"} /></em></h2><p><LocalizedText source={"Simple connected steps turn farm and trade data into better decisions."} /></p></div><ol><li><b>01</b><span><strong><LocalizedText source={"Assess & connect"} /></strong><small><LocalizedText source={"Capture the farm, soil, crop, quality, buyer, and delivery context."} /></small></span></li><li><b>02</b><span><strong><LocalizedText source={"Run intelligent models"} /></strong><small><LocalizedText source={"Compare recommendations, freshness, credit, supplier matches, and routes."} /></small></span></li><li><b>03</b><span><strong><LocalizedText source={"Act with confidence"} /></strong><small><LocalizedText source={"Use transparent evidence and economics to plan, buy, sell, and deliver."} /></small></span></li></ol></section>
      <section className="landing-impact" id="impact"><div className="landing-section-head"><span><LocalizedText source={"Platform connected today"} /></span><h2><LocalizedText source={"Real data. Working models. One experience."} /></h2></div><div>{[["3","Verified farmers"],["5","Available listings"],["400","Buyer profiles"],["7","Connected engines"]].map(([v,l])=><span key={l}><b><LocalizedText source={"{0}"} values={[v]} /></b><small><LocalizedText source={"{0}"} values={[l]} /></small></span>)}</div></section>
      <section className="landing-stories" id="stories"><span><LocalizedText source={"Choose your workspace"} /></span><h2><LocalizedText source={"Built for both sides of agricultural trade."} /></h2><div><article><i>👨🏽‍🌾</i><h3><LocalizedText source={"Farmer workspace"} /></h3><p><LocalizedText source={"Plan crops, check freshness, publish produce, test buyer matching, and optimize delivery."} /></p><button onClick={()=>openPortal("farmer")}><LocalizedText source={"Enter farmer portal →"} /></button></article><article><i>🏢</i><h3><LocalizedText source={"Buyer workspace"} /></h3><p><LocalizedText source={"Discover farmer supply, assess credit, rank suppliers, and optimize procurement economics."} /></p><button onClick={()=>openPortal("buyer")}><LocalizedText source={"Enter buyer portal →"} /></button></article></div></section>
    </main><footer className="landing-footer"><div><b><LocalizedText source={"AgriOptimaᴬᴵ."} /></b><p><LocalizedText source={"Connected agricultural intelligence for stronger farms and smarter procurement."} /></p></div><div><button onClick={()=>openPortal("farmer")}><LocalizedText source={"Farmer portal"} /></button><button onClick={()=>openPortal("buyer")}><LocalizedText source={"Buyer portal"} /></button></div><small><LocalizedText source={"© 2026 AgriOptimaᴬᴵ. Decision-support platform."} /></small></footer>
    {portal&&<div className="portal-modal" onClick={()=>setPortal(false)}><div onClick={e=>e.stopPropagation()}><button className="portal-x" onClick={()=>setPortal(false)}>×</button><span><LocalizedText source={"Instant demo access"} /></span><h2><LocalizedText source={"Choose your AgriOptimaᴬᴵ workspace"} /></h2><p><LocalizedText source={"Both portals are connected to the same farmer data and intelligence engines."} /></p><div><button onClick={()=>openPortal("farmer")}><i>👨🏽‍🌾</i><b><LocalizedText source={"Farmer portal"} /></b><small><LocalizedText source={"Plan, grade, list, match, and deliver"} /></small><em><LocalizedText source={"Open workspace →"} /></em></button><button onClick={()=>openPortal("buyer")}><i>🏢</i><b><LocalizedText source={"Buyer portal"} /></b><small><LocalizedText source={"Discover, assess, procure, and optimize"} /></small><em><LocalizedText source={"Open workspace →"} /></em></button></div></div></div>}
  </div>;
}
