import { useEffect, useState } from "react";

export default function LandingPage({ onBuyer, onFarmer }: { onBuyer:()=>void; onFarmer:()=>void }) {
  const [menu,setMenu]=useState(false); const [scrolled,setScrolled]=useState(false); const [portal,setPortal]=useState(false);
  useEffect(()=>{const handler=()=>setScrolled(window.scrollY>25);window.addEventListener("scroll",handler,{passive:true});return()=>window.removeEventListener("scroll",handler)},[]);
  const openPortal=(kind:"buyer"|"farmer")=>{setMenu(false);setPortal(false);if(kind==="buyer") onBuyer(); else onFarmer()};
  return <div className="agrovia-landing">
    <header className={`landing-header ${scrolled?"scrolled":""}`}><div className="landing-nav"><a href="#top" className="landing-logo">AgriOptima.</a><nav><a href="#solutions">Solutions</a><a href="#platform">How it works</a><a href="#impact">Our impact</a><a href="#stories">Farmer stories</a><button className="live-pill" onClick={()=>setPortal(true)}><i/> Live platform</button></nav><div className="landing-actions"><button className="language-button">EN⌄</button><button onClick={()=>setPortal(true)} className="login-button">Log in</button><button onClick={()=>setPortal(true)} className="get-started">Get started</button></div><div className="landing-mobile"><button className="language-button">EN⌄</button><button id="mobile-menu-toggle-btn" aria-expanded={menu} aria-controls="landing-mobile-menu" onClick={()=>setMenu(!menu)} className="burger-button"><span/><span/><span/></button></div></div>
      {menu&&<div id="landing-mobile-menu" className="landing-mobile-menu"><a onClick={()=>setMenu(false)} href="#solutions">Solutions</a><a onClick={()=>setMenu(false)} href="#platform">How it works</a><a onClick={()=>setMenu(false)} href="#impact">Our impact</a><a onClick={()=>setMenu(false)} href="#stories">Farmer stories</a><button className="mobile-live" onClick={()=>setPortal(true)}><span><i/> Live platform</span>→</button><div><button onClick={()=>setPortal(true)}>Log in</button><button onClick={()=>setPortal(true)}>Get started</button></div></div>}
    </header>
    <main id="top"><section className="landing-hero"><div className="hero-backdrop"/><div className="landing-hero-copy"><span><i/> Connected agricultural intelligence</span><h1>Smarter technology<br/><em>for stronger</em><br/>agriculture</h1><p>Connect farm planning, verified supply, AI freshness, buyer credit, supplier matching, and optimized logistics in one transparent platform.</p><div><button onClick={()=>setPortal(true)}>Get started today →</button><a href="#platform">See how it works ▷</a></div><small>Built for farmers, buyers, FPOs, and agricultural supply networks.</small></div></section>
      <section className="landing-intro" id="platform"><span>Introducing AgriOptima</span><h2>Bringing intelligence to every step of agriculture —</h2><p>We connect farmer data, crop decisions, quality verification, market demand, procurement credit, supplier rankings, and transport economics. Every workflow is explainable, evidence-based, and designed for real production and trade decisions.</p><button onClick={()=>setPortal(true)}>Explore the connected platform →</button></section>
      <section className="landing-solutions" id="solutions"><div className="landing-section-head"><span>Connected solutions</span><h2>Smart tools for modern farming and procurement</h2><p>One platform. Two purpose-built workspaces. Every model connected.</p></div><div className="solution-grid">{[
        ["🌱","Crop intelligence","Filter infeasible crops and compare transparent opportunity scores.","Farmer planning"],["🍅","AI freshness grading","Grade tomato freshness and inspect produce shipments from images.","Quality assurance"],["📊","Smart procurement","Rank farmer lots against buyer price, quality, quantity, and freshness requirements.","Buyer matching"],["💳","Credit intelligence","Explain buyer risk, repayment behaviour, confidence, and revolving limits.","Trade finance"],["🚚","Logistics optimization","Compare direct, pooled, and collection-hub models with final landed cost.","Supply chain"],["🧺","Verified marketplace","Connect real farmer profiles, farms, needs, and active produce listings.","Market access"],
      ].map(([icon,title,copy,tag])=><article key={title}><span>{icon}</span><small>{tag}</small><h3>{title}</h3><p>{copy}</p><button onClick={()=>setPortal(true)}>Open live demo →</button></article>)}</div></section>
      <section className="landing-process"><div><span>The AgriLoop process</span><h2>Farming smarter<br/><em>starts here</em></h2><p>Simple connected steps turn farm and trade data into better decisions.</p></div><ol><li><b>01</b><span><strong>Assess & connect</strong><small>Capture the farm, soil, crop, quality, buyer, and delivery context.</small></span></li><li><b>02</b><span><strong>Run intelligent models</strong><small>Compare recommendations, freshness, credit, supplier matches, and routes.</small></span></li><li><b>03</b><span><strong>Act with confidence</strong><small>Use transparent evidence and economics to plan, buy, sell, and deliver.</small></span></li></ol></section>
      <section className="landing-impact" id="impact"><div className="landing-section-head"><span>Platform connected today</span><h2>Real data. Working models. One experience.</h2></div><div>{[["3","Verified farmers"],["5","Available listings"],["400","Buyer profiles"],["7","Connected engines"]].map(([v,l])=><span key={l}><b>{v}</b><small>{l}</small></span>)}</div></section>
      <section className="landing-stories" id="stories"><span>Choose your workspace</span><h2>Built for both sides of agricultural trade.</h2><div><article><i>👨🏽‍🌾</i><h3>Farmer workspace</h3><p>Plan crops, check freshness, publish produce, test buyer matching, and optimize delivery.</p><button onClick={()=>openPortal("farmer")}>Enter farmer portal →</button></article><article><i>🏢</i><h3>Buyer workspace</h3><p>Discover farmer supply, assess credit, rank suppliers, and optimize procurement economics.</p><button onClick={()=>openPortal("buyer")}>Enter buyer portal →</button></article></div></section>
    </main><footer className="landing-footer"><div><b>AgriOptima.</b><p>Connected agricultural intelligence for stronger farms and smarter procurement.</p></div><div><button onClick={()=>openPortal("farmer")}>Farmer portal</button><button onClick={()=>openPortal("buyer")}>Buyer portal</button></div><small>© 2026 AgriOptima AI. Decision-support platform.</small></footer>
    {portal&&<div className="portal-modal" onClick={()=>setPortal(false)}><div onClick={e=>e.stopPropagation()}><button className="portal-x" onClick={()=>setPortal(false)}>×</button><span>Instant demo access</span><h2>Choose your AgriOptima workspace</h2><p>Both portals are connected to the same farmer data and intelligence engines.</p><div><button onClick={()=>openPortal("farmer")}><i>👨🏽‍🌾</i><b>Farmer portal</b><small>Plan, grade, list, match, and deliver</small><em>Open workspace →</em></button><button onClick={()=>openPortal("buyer")}><i>🏢</i><b>Buyer portal</b><small>Discover, assess, procure, and optimize</small><em>Open workspace →</em></button></div></div></div>}
  </div>;
}
