"""create team1 farmer intelligence tables

Revision ID: 2f3fb1901ab2
Revises: 
Create Date: 2026-08-31 20:25:16.167576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f3fb1901ab2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_data_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('farmers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('village', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('farms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('area_acres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('irrigation', sa.String(length=16), nullable=False),
    sa.Column('soil_ph', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('nitrogen', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phosphorus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('potassium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('soil_source', sa.String(length=64), nullable=False),
    sa.Column('soil_test_date', sa.Date(), nullable=True),
    sa.Column('previous_crop', sa.String(length=64), nullable=False),
    sa.Column('investment_budget_paise', sa.BigInteger(), nullable=False),
    sa.Column('sowing_period', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("irrigation IN ('none', 'limited', 'adequate')", name='check_irrigation_values'),
    sa.CheckConstraint('area_acres > 0', name='check_area_acres_positive'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('crop_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('farm_id', sa.BigInteger(), nullable=False),
    sa.Column('crop', sa.String(length=64), nullable=False),
    sa.Column('opportunity_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='check_confidence_range'),
    sa.CheckConstraint('opportunity_score BETWEEN 0 AND 100', name='check_opportunity_score_range'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crop_recommendations')
    op.drop_table('farms')
    op.drop_table('farmers')
    op.drop_table('external_data_cache')
    # ### end Alembic commands ###
